[nfs]
172.31.30.252 ansible_ssh_user='ec2-user'

[webservers]
172.31.16.251 ansible_ssh_user='ec2-user'
172.31.21.178 ansible_ssh_user='ec2-user'

[db]
172.31.17.181 ansible_ssh_user='ubuntu' 

[lb]
172.31.19.46 ansible_ssh_user='ubuntu'
